In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

Creating a method to set Not assigned Neighborhoods with the name of the Borough

In [2]:
def neighborhoodCleansing(row):
   a = row['Borough']
   b = row['Neighborhood']
   
   if b == 'Not assigned':
     return a
   else:
     return b

<li>
    <ol>Reading the data from Wikipedia</ol>
    <ol>Cleaning all the post codes that were not assigned to any Borough </ol>
    <ol>Renaming columns</ol>
    <ol>Grouping Neighborhoods of the same Borough</ol>
    <ol>Display the first eleven lines</ol>
</li>

In [3]:

table = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M',
                      index_col=0, header=0, match='Postcode')

toronto = table[0]
toronto.reset_index(inplace=True)
toronto = toronto[toronto['Borough']!='Not assigned']
toronto['Neighborhood'] = toronto.apply(lambda row: neighborhoodCleansing(row),axis=1)
toronto.rename(columns={'Postcode':'PostalCode'},inplace=True)
toronto = toronto.groupby(['PostalCode','Borough']).Neighborhood.agg([('Neighborhood', ', '.join)])
toronto.reset_index(inplace=True)
toronto.head(11)

   PostalCode      Borough                                       Neighborhood
0         M1B  Scarborough                                     Rouge, Malvern
1         M1C  Scarborough             Highland Creek, Rouge Hill, Port Union
2         M1E  Scarborough                  Guildwood, Morningside, West Hill
3         M1G  Scarborough                                             Woburn
4         M1H  Scarborough                                          Cedarbrae
5         M1J  Scarborough                                Scarborough Village
6         M1K  Scarborough        East Birchmount Park, Ionview, Kennedy Park
7         M1L  Scarborough                    Clairlea, Golden Mile, Oakridge
8         M1M  Scarborough    Cliffcrest, Cliffside, Scarborough Village West
9         M1N  Scarborough                        Birch Cliff, Cliffside West
10        M1P  Scarborough  Dorset Park, Scarborough Town Centre, Wexford ...

In [4]:
toronto.shape

(103, 3)

End of part one

Begin of part two

Creating methdos to retrieve the Latitude and Longitude using the API

In [5]:
import geocoder # import geocoder

def getLatitude(row):
   postal_code = row['PostalCode']
   # initialize your variable to None
   lat_lng_coords = None

   # loop until you get the coordinates
   while(lat_lng_coords is None):
     g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
     
     lat_lng_coords = g.latlng
   latitude = lat_lng_coords[0]
           
   return latitude

def getLongitude(row):
   postal_code = row['PostalCode']
   # initialize your variable to None
   lat_lng_coords = None

   # loop until you get the coordinates
   while(lat_lng_coords is None):
     g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
     
     lat_lng_coords = g.latlng
   longitude = lat_lng_coords[1]
   return longitude

Creating the columns Latitude and Longitude and filling with data using the API

In [6]:
#toronto[['Latitude']] = toronto.apply(lambda row: getLatitude(row),axis=1)
#toronto[['Longitude']] = toronto.apply(lambda row: getLongitude(row),axis=1)

The API did not respond, so I have to read the coordinates from the csv file

In [7]:
coordinates = pd.read_csv('https://cocl.us/Geospatial_data')
coordinates.rename(columns={'Postal Code':'PostalCode'},inplace=True)
coordinates

    PostalCode   Latitude  Longitude
0          M1B  43.806686 -79.194353
1          M1C  43.784535 -79.160497
2          M1E  43.763573 -79.188711
3          M1G  43.770992 -79.216917
4          M1H  43.773136 -79.239476
..         ...        ...        ...
98         M9N  43.706876 -79.518188
99         M9P  43.696319 -79.532242
100        M9R  43.688905 -79.554724
101        M9V  43.739416 -79.588437
102        M9W  43.706748 -79.594054

[103 rows x 3 columns]

Merging the toronto dataframe with the coordinates dataframe to include the Latitude and Longitude columns

In [8]:
toronto = pd.merge(toronto, coordinates, on='PostalCode')
toronto

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
1,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, Martin Grove Gardens, Richv...",43.688905,-79.554724
101,M9V,Etobicoke,"Albion Gardens, Beaumond Heights, Humbergate, ...",43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054

End of part two